language: generic
os: linux

branches:
  only:
  - master

services:
- docker

env:
  global:
  - NJOBS="2"
  - CONTRIB="analysis"
  - OPAMYES=yes
  jobs:
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.10"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.11"

install:
- docker pull ${DOCKERIMAGE}
- docker tag  ${DOCKERIMAGE} ci:current
- docker run  --env=OPAMYES --init -id --name=CI -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB} -w /home/coq/${CONTRIB} ci:current
- docker exec CI /bin/bash --login -c "cd ..; curl -LO https://github.com/math-comp/finmap/archive/1.5.0.tar.gz; tar -xvzf 1.5.0.tar.gz; cd finmap-1.5.0/; opam pin add -y -n coq-mathcomp-finmap.1.5.0 .; opam install coq-mathcomp-finmap.1.5.0; cd /home/coq/${CONTRIB}"
- docker exec CI /bin/bash --login -c "opam pin add -y -n coq-mathcomp-${CONTRIB} ."
- docker exec CI /bin/bash --login -c "opam install --deps-only coq-mathcomp-${CONTRIB}"

script:
- docker exec CI /bin/bash --login -c "opam install -vvv coq-mathcomp-${CONTRIB}"
