defaults:
  params: &params
    working_directory: ~/build
    docker:
      - image: ocaml/opam:ubuntu
        environment:
          OPAMJOBS: 2
          OPAMVERBOSE: y
          OPAMYES: true
          OPAMSTATUSLINE: never
          OPAMSWITCH: ci
          TERM: xterm

version: 2

before_script: &before_script
  name: Configure Base System
  command: |
    printenv

.opam-boot-template: &opam-boot-template
  <<: *params
  steps:
    - checkout
    - run: *before_script
    - run:
        name: Install opam remotes
        command: |
          env -u OPAMSWITCH opam remote add dist-default  https://opam.ocaml.org
          env -u OPAMSWITCH opam remote add coq-released  http://coq.inria.fr/opam/released
          env -u OPAMSWITCH opam remote add coq-core-dev  http://coq.inria.fr/opam/core-dev
          env -u OPAMSWITCH opam remote add coq-extra-dev http://coq.inria.fr/opam/extra-dev
    - run:
        name: Cache selection
        command: |
          rm -f deps.ver
          echo "compiler.${COMPILER}-" > "deps.ver"
          echo "coq.${COQVERSION}-" >> "deps.ver"
          echo "mathcomp.${MATHCOMPVERSION}-" >> "deps.ver"
          echo "bigenough.${BIGENOUGHVERSION}-" >> "deps.ver"
          echo "finmap.${FINMAPVERSION}-" >> "deps.ver"
          cat deps.ver
    - restore_cache:
        keys:
          - opam-cache-v5-{{ checksum ".circleci/config.yml" }}-${{ checksum "deps.ver" }}-
    - run:
        name: Install opam switch
        command: |
          env -u OPAMSWITCH opam switch -A ${COMPILER} ${OPAMSWITCH}
    - run:
        name: Update opam remotes
        command: |
          env -u OPAMSWITCH opam update
    - run:
        name: Install Coq
        command: |
          env -u OPAMSWITCH opam pin add -n coq ${COQVERSION}
          env -u OPAMSWITCH opam install coq
    - run:
        name: Install MathComp
        command: |
          env -u OPAMSWITCH opam pin add -n coq-mathcomp-ssreflect ${MATHCOMPVERSION}
          env -u OPAMSWITCH opam pin add -n coq-mathcomp-bigenough ${BIGENOUGHVERSION}
          env -u OPAMSWITCH opam pin add -n coq-mathcomp-finmap ${FINMAPVERSION}
          env -u OPAMSWITCH opam install coq-mathcomp-ssreflect coq-mathcomp-bigenough coq-mathcomp-finmap ${MATHCOMPPKG}
    - run:
        name: Clean cache
        command: |
          rm -rf ~/.opam/log/
    - save_cache:
        key: opam-cache-v5-{{ checksum ".circleci/config.yml" }}-${{ checksum "deps.ver" }}-
        paths:
          - ~/.opam
    - persist_to_workspace:
        root: &workspace ~/
        paths:
          - .opam/

jobs:
  opam-boot:
    <<: *opam-boot-template
    environment:
      COMPILER: 4.05.0
      COQVERSION: 8.8.0
      MATHCOMPVERSION: 1.7.0
      BIGENOUGHVERSION: 1.0.0
      FINMAPVERSION: 1.1.0
      MATHCOMPPKG: coq-mathcomp-algebra coq-mathcomp-field

  build:
    <<: *params
    steps:
      - checkout
      - run: *before_script
      - attach_workspace: &attach_workspace
          at: *workspace
      - run:
          name: Building
          command: |
             opam config exec make
      - persist_to_workspace:
          root: *workspace
          paths:
            - build/

workflows:
  version: 2
  main:
    jobs:
      - opam-boot
      - build:
         requires:
           - opam-boot
