(* mathcomp analysis (c) 2026 Inria and AIST. License: CeCILL-C.              *)
From HB Require Import structures.
From mathcomp Require Import all_ssreflect_compat algebra all_classical finmap.
#[warning="-warn-library-file-internal-analysis"]
From mathcomp Require Import unstable.
From mathcomp Require Import interval_inference reals topology_structure.
From mathcomp Require Import uniform_structure order_topology.
From mathcomp Require Import pseudometric_structure.

(**md**************************************************************************)
(* # Initial topology                                                         *)
(*                                                                            *)
(* This file defines the initial topology for $S$ by a function $f$ whose     *)
(* domain is $S$. This topology is also known as initial topology on $S$ with *)
(* respect to $f$.                                                            *)
(*                                                                            *)
(* NB: Before version 1.16.0, the initial topology was called the weak        *)
(* topology. Though in some literature (e.g., Wilansky) it can be called that *)
(* way, we reserve "weak topology" for the topology induced on a topological  *)
(* vector space by its dual.                                                  *)
(*                                                                            *)
(* ```                                                                        *)
(*          initial_topology f == initial topology by a function f : S -> T   *)
(*                                on S                                        *)
(*                                S must be a choiceType and T a              *)
(*                                topologicalType.                            *)
(*  sub_initial_topology V S U == sub-initial topology generated by the       *)
(*                                \val : U -> V                               *)
(*                                U has type subChoiceType S with S : pred V. *)
(*                                This is a subTopologicalType when V is      *)
(*                                endowed with a topology.                    *)
(*                                This is a subConvexTvsType when V is        *)
(*                                endowed with a convexTvsType (and when U is *)
(*                                subLmodType).                               *)
(*      initial_fam_topology f == initial topology by a family of functions   *)
(*                              F : (I -> (S -> T).                           *)
(*                                I must be a pointedType, S a choiceType     *)
(*                                and T a topologicalType.                    *)
(* ```                                                                        *)
(* `initial_topology` is equipped with the structures of:                     *)
(* - uniform space                                                            *)
(* - pseudometric space (the metric space for initial topologies)             *)
(******************************************************************************)

Import Order.TTheory GRing.Theory Num.Theory.

Unset SsrOldRewriteGoalsOrder.  (* remove the line when requiring MathComp >= 2.6 *)
Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Local Open Scope classical_set_scope.
Local Open Scope ring_scope.

Definition initial_topology {S : Type} {T : Type}
  (f : S -> T) : Type := S.

Section Initial_Topology.
Variable (S : choiceType) (T : topologicalType) (f : S -> T).
Local Notation W := (initial_topology f).

Definition initial_open := [set f @^-1` A | A in open].

Let initial_opT : initial_open [set: W].
Proof. by exists setT => //; exact: openT. Qed.

Let initial_opI : setI_closed initial_open.
Proof.
by move=> ? ? [C Cop <-] [D Dop <-]; exists (C `&` D) => //; exact: openI.
Qed.

Let initial_op_bigU (I : Type) (g : I -> set W) :
  (forall i, initial_open (g i)) -> initial_open (\bigcup_i g i).
Proof.
move=> gop.
set opi := fun i => [set Ui | open Ui /\ g i = f @^-1` Ui].
exists (\bigcup_i get (opi i)).
  apply: bigcup_open => i.
  by have /getPex [] : exists U, opi i U by have [U] := gop i; exists U.
have g_preim i : g i = f @^-1` (get (opi i)).
  by have /getPex [] : exists U, opi i U by have [U] := gop i; exists U.
rewrite predeqE => s; split=> [[i _]|[i _]]; last by rewrite g_preim; exists i.
by rewrite -[_ _]/((f @^-1` _) _) -g_preim; exists i.
Qed.

HB.instance Definition _ := Choice.on W.
HB.instance Definition _ :=
  isOpenTopological.Build W initial_opT initial_opI initial_op_bigU.

Lemma initial_continuous : continuous (f : W -> T).
Proof. by apply/continuousP => A ?; exists A. Qed.

(* TODO : use image_set_system to be imported from measure theory *)
Lemma cvg_initial (F : set_system S) (s : S) :
  Filter F ->
 ([set f @` A | A in F] : set_system _) --> f s ->  F --> (s : W).
Proof.
move=> FF cvfFfs.
move=> A /= [_ [[B Bop <-] Bfs sBfA]].
have /cvfFfs [C FC fCeB] : nbhs (f s) B by rewrite nbhsE; exists B.
rewrite nbhs_filterE; apply: filterS FC.
by apply: subset_trans sBfA; rewrite -fCeB; apply: preimage_image.
Qed.

Lemma cvg_image (F : set_system S) (s : S) :
  Filter F -> f @` setT = setT ->
  F --> (s : W) <-> ([set f @` A | A in F] : set_system _) --> f s.
Proof.
move=> FF fsurj; split=> [cvFs|/cvg_initial //].
move=> A /initial_continuous [B [Bop Bs sBAf]].
have /cvFs FB : nbhs (s : W) B by apply: open_nbhs_nbhs.
rewrite nbhs_simpl; exists (f @^-1` A); first exact: filterS FB.
by exact: image_preimage.
Qed.

Lemma continuous_initial_topology (U : topologicalType) (g : U -> W):
  continuous g <-> (continuous (f \o g)).
Proof.
split => cont x.
  apply: continuous_comp; first by apply: cont.
  by apply: initial_continuous.
move => A [B/=]; rewrite /initial_topology /= => -[[C] oC fBC] Bgx BA.
apply: filterS; first by exact: BA.
rewrite -fBC /nbhs -comp_preimage.
apply: cont; apply: open_nbhs_nbhs; split => //.
have : f @` B `<=` C by move => z /= [t]; rewrite -fBC //= => ? <-.
by apply => /=; exists (g x).
Qed.

End Initial_Topology.
(*#[deprecated(since="mathcomp-analysis 1.17.0", note="renamed `initial_open`")]
Notation wopen := initial_open (only parsing).*)

HB.instance Definition _ (S : pointedType) (T : topologicalType) (f : S -> T) :=
  Pointed.on (initial_topology f).

Definition sub_initial_topology (V : Type) (S : pred V) (U : subChoiceType S)
  : Type := initial_topology (\val : U -> V).

Section SubType_isSubTopological.
Context (V : topologicalType) (S : pred V) (U : subChoiceType S).

Local Notation T := (sub_initial_topology U).
HB.instance Definition _ := SubChoice.on T.
HB.instance Definition _ := Nbhs.on T.
HB.instance Definition _ := Topological.on T.

Let top_continuous_valE : continuous (val : T -> V).
Proof. exact: initial_continuous. Qed.

HB.instance Definition _ := @isSubNbhs.Build V S T top_continuous_valE.

End SubType_isSubTopological.

Section initial_uniform.
Local Open Scope relation_scope.
Variable (pS : choiceType) (U : uniformType) (f : pS -> U).

Let S := initial_topology f.

Definition initial_ent : set_system (S * S) :=
  filter_from (@entourage U) (fun V => (map_pair f)@^-1` V).

Let initial_ent_filter : Filter initial_ent.
Proof.
apply: filter_from_filter; first by exists setT; exact: entourageT.
by move=> P Q ??; (exists (P `&` Q); first exact: filterI) => ?.
Qed.

Let initial_ent_refl A : initial_ent A -> diagonal `<=` A.
Proof.
by move=> [B ? sBA] [x y]/diagonalP ->; apply/sBA; exact: entourage_refl.
Qed.

Let initial_ent_inv A : initial_ent A -> initial_ent A^-1.
Proof.
move=> [B ? sBA]; exists B^-1; first exact: entourage_inv.
by move=> ??; exact/sBA.
Qed.

Let initial_ent_split A : initial_ent A -> exists2 B, initial_ent B & B \; B `<=` A.
Proof.
move=> [B entB sBA]; have : exists C, entourage C /\ C \; C `<=` B.
  exact/exists2P/entourage_split_ex.
case=> C [entC CsubB]; exists ((map_pair f)@^-1` C); first by exists C.
by case=> x y [a ? ?]; apply/sBA/CsubB; exists (f a).
Qed.

Let initial_ent_nbhs : nbhs = nbhs_ initial_ent.
Proof.
rewrite predeq2E => x V; split.
  case=> [? [[B  ? <-] ? BsubV]]; have: nbhs (f x) B by apply: open_nbhs_nbhs.
  move=> /nbhsP [W ? WsubB]; exists ((map_pair f) @^-1` W); first by exists W.
  by move=> ? ?; exact/BsubV/WsubB.
case=> W [V' entV' V'subW] /filterS; apply.
have : nbhs (f x) (xsection V' (f x)) by apply/nbhsP; exists V'.
rewrite (@nbhsE U) => [[O [openU Ofx Osub]]].
(exists (f @^-1` O); repeat split => //); first by exists O => //.
by move=> w ?; apply/mem_set; apply: V'subW; apply/set_mem; exact: Osub.
Qed.

HB.instance Definition _ := @Nbhs_isUniform.Build (initial_topology f)
  initial_ent initial_ent_filter initial_ent_refl initial_ent_inv
  initial_ent_split initial_ent_nbhs.

End initial_uniform.

HB.instance Definition _ (pS : pointedType) (U : uniformType) (f : pS -> U) :=
  Pointed.on (initial_topology f).

Section initial_pseudoMetric.
Context {R : realType} (pS : choiceType) (U : pseudoMetricType R) .
Variable (f : pS -> U).

Notation S := (initial_topology f).

Definition initial_ball (x : S) (r : R) (y : S) := ball (f x) r (f y).

Let initial_pseudo_metric_ball_center (x : S) (e : R) : 0 < e ->
  initial_ball x e x.
Proof. by move=> /posnumP[{}e]; exact: ball_center. Qed.

Let initial_pseudo_metric_entourageE : entourage = entourage_ initial_ball.
Proof.
rewrite /entourage /= /initial_ent -entourage_ballE /entourage_.
have -> : (fun e => [set xy | ball (f xy.1) e (f xy.2)]) =
   (preimage (map_pair f) \o fun e => [set xy | ball xy.1 e xy.2])%FUN.
  by [].
rewrite eqEsubset; split; apply/filter_fromP.
- apply: filter_from_filter; first by exists 1 => /=.
  move=> e1 e2 e1pos e2pos; wlog e1lee2 : e1 e2 e1pos e2pos / e1 <= e2.
    by have [?|/ltW ?] := lerP e1 e2; [exact | rewrite setIC; exact].
  exists e1 => //; rewrite -preimage_setI; apply: preimage_subset.
  by move=> ? ?; split => //; apply: le_ball; first exact: e1lee2.
- by move=> E [e ?] heE; exists e => //; apply: preimage_subset.
- apply: filter_from_filter.
    by exists [set xy | ball xy.1 1 xy.2]; exists 1 => /=.
  move=> E1 E2 [e1 e1pos he1E1] [e2 e2pos he2E2].
  wlog ? : E1 E2 e1 e2 e1pos e2pos he1E1 he2E2 / e1 <= e2.
    have [? /(_ _ _ e1 e2)|/ltW ? ] := lerP e1 e2; first exact.
    by rewrite setIC => /(_ _ _ e2 e1); exact.
  exists (E1 `&` E2) => //; exists e1 => // xy /= B; split; first exact: he1E1.
  by apply/he2E2/le_ball; last exact: B.
- by move=> e ?; exists [set xy | ball xy.1 e xy.2] => //; exists e => /=.
Qed.

HB.instance Definition _ := Uniform_isPseudoMetric.Build R S
  initial_pseudo_metric_ball_center (fun _ _ _ => @ball_sym _ _ _ _ _)
  (fun _ _ _ _ _ => @ball_triangle _ _ _ _ _ _ _)
  initial_pseudo_metric_entourageE.

Lemma initial_ballE (e : R) (x : S) : f @^-1` (ball (f x) e) = ball x e.
Proof. by []. Qed.

End initial_pseudoMetric.

(** for an orderedTopologicalType T, and subtype U
    (order_topology (sub_type U)) `<=` (initial_topology (sub_type U))
    but generally the topologies are not equal!
    Consider `[0,1[ | {2}` as a subset of `[0,3]` for an example
*)
Section initial_order_refine.
Context {d} {X : orderTopologicalType d} {Y : subType X}.

Let OrdU : orderTopologicalType d := order_topology (sub_type Y).
Let InitialU : topologicalType := @initial_topology (sub_type Y) X val.

Lemma open_order_initial (U : set Y) : @open OrdU U -> @open InitialU U.
Proof.
rewrite ?openE /= /interior => + x Ux => /(_ x Ux); rewrite itv_nbhsE /=.
move=> [][][[]l|[]] [[]r|[]][]//= _ xlr /filterS; apply.
- exists `]l, r[%classic; split => //=; exists `]\val l, \val r[%classic.
    exact: itv_open.
  by rewrite eqEsubset; split => z; rewrite preimage_itv.
- exists `]l, +oo[%classic; split => //=; exists `]\val l, +oo[%classic.
    exact: rray_open.
  by rewrite eqEsubset; split => z; rewrite preimage_itv.
- exists `]-oo, r[%classic; split => //=; exists `]-oo, \val r[%classic.
    exact: lray_open.
  by rewrite eqEsubset; split => z; rewrite preimage_itv.
- by rewrite set_itvE; exact: filterT.
Qed.

End initial_order_refine.

Lemma continuous_comp_initial {Y : choiceType} {X Z : topologicalType}
  (w : Y -> Z) (f : X -> initial_topology w) :
  continuous (w \o f) -> continuous f.
Proof.
move=> cf z U [?/= [[W oW <-]]] /= Wsfz /filterS; apply; apply: cf.
exact: open_nbhs_nbhs.
Qed.

Lemma bigsetI_open (U : topologicalType) (I: Type) (s : seq I) (P : pred I) (f : I -> set U) :
 (forall i, P i ->  open (f i)) ->  open (\big[setI/setT]_(i<- s | P i) f i).
Proof.
move=> Pf. apply: big_ind => //. by apply: openT. exact: openI.
Qed.

Definition initial_fam_topology {S : Type} {T : Type} {I : pointedType}
  (F : I -> (S -> T)) : Type := S.

Section initial_fam_topology.
Variable (S : choiceType) (T : topologicalType) (I : pointedType)  (F : I -> (S -> T)).
Local Notation W := (initial_fam_topology F).

Definition init_fam_subbase := [set O | exists i, exists2 A, (O = (F i) @^-1` A) & open A  ].

HB.instance Definition _ := Choice.on W.
HB.instance Definition _ := isSubBaseTopological.Build W init_fam_subbase id.

Lemma initial_fam_continuous : forall i, continuous ((F i) : W -> T).
Proof. move=> i; apply/continuousP => A oA.
exists [set  (F i @^-1` A)]; last by rewrite bigcup_set1.
move=> /= O /= -> /= . rewrite /finI_from /=.
exists [fset  (F i @^-1` A)]%fset; last by rewrite set_fset1 bigcap_set1.
by move => ? /=; rewrite inE; move/eqP ->; rewrite /init_fam_subbase in_setE /=; exists i; exists A.
Qed.

Lemma cvg_init_fam (G : set_system W) (s : W) :
  Filter G ->
  (forall i, ([set (F i)  @` A | A in G] : set_system _) --> F i s) ->  G --> (s : W) .
Proof.
move=> FG cvfFfs.
move => A -[] /=.
move => _  [[]] H Hop <- [B HB Bs] sBfA/=; rewrite nbhs_filterE.
have BA : B `<=` A.
  apply: subset_trans; last by exact: sBfA.
  by move => y /= By; exists B =>//.
apply: (@filterS _ G _  B) => //; move /(_ B HB): Hop  => /= [] /= C CO Bcap.
(* can´t  apply fsubsetP or subsetP on CO  to obtain the following *)
have Ci : forall (O : set S) , O \in C ->
  exists i : I, exists2 A : set T, O = F i @^-1` A & open A.
  by move => O /CO /set_mem //=.
move => {CO} {sBfA} {BA} {A}.
have GC: forall (O : set S), O \in C -> G O.
  move => O OC; move: (OC) => /Ci [i [D OD openD]].
  have : nbhs (F i s) D.
    rewrite nbhsE; exists D => //; split => //.
    by move: Bs; rewrite -Bcap /bigcap /= => /(_ O OC); rewrite OD.
  move/(cvfFfs i D); rewrite nbhs_filterE => //= [[O']] GO' /= O'D.
  apply: filterS; last by exact: GO'.
  by rewrite OD -O'D; apply: preimage_image.
by rewrite -Bcap; apply: filter_bigI => /= O OC; apply: GC.
Qed.

Lemma cvg_image_init_fam (G : set_system W) (s : W) :
  Filter G -> (forall i, (F i) @` setT = setT) ->
  G --> (s : W) <-> (forall i, ([set (F i)  @` A | A in G] : set_system _) --> F i s).
Proof.
move=> FG fsurj; split=> [cvFs|/cvg_init_fam] //.
move=> i A /initial_fam_continuous [B [//= Bop Bs sBAf]].
have /cvFs FB : nbhs (s : W) B by apply: open_nbhs_nbhs.
rewrite nbhs_simpl; exists ((F i) @^-1` A); first exact: filterS FB.
by exact: image_preimage.
Qed.

Lemma continuous_init_fam (V : topologicalType) (f : V -> W) :
 (forall i, continuous ((F i) \o (f : V -> S))) <-> continuous f.
Proof.
split=> cont; last first.
  move=> i x; apply: continuous_comp; first by apply: cont.
  apply: initial_fam_continuous.
move => x A; rewrite /nbhs /= => -[/= B] [Bfrom Bfx BA] /=.
apply: filterS; first by apply: preimage_subset BA.
apply: open_nbhs_nbhs; split => //.
have:= Bfrom => -[] C CO <-; rewrite preimage_bigcup.
apply: bigcup_open => i /CO [] /= D Dsub <-; rewrite preimage_bigcap /=.
rewrite bigcap_fset /= big_seq; apply: bigsetI_open => /= E /Dsub.
move/set_mem; rewrite /init_fam_subbase /= => -[j [A0 -> oA]].
rewrite -comp_preimage.
by have /continuousP := cont j; apply.
Qed.

End initial_fam_topology.


HB.instance Definition _ (S : pointedType) (T : topologicalType)  (I : pointedType)  (F : I -> (S -> T)) :=
  Pointed.on (initial_fam_topology F).
HB.instance Definition _ (S : pointedType) (T : topologicalType)  (I : pointedType)  (F : I -> (S -> T)) :=
  Filtered.on (initial_fam_topology F).


Section initial_fam_topology_uniform.

Local Open Scope relation_scope.
Variable (S : choiceType) (T : uniformType) (I : pointedType) (F : I -> (S -> T)).

Let W := initial_fam_topology F.

Definition initial_fam_ent : set_system (W * W) :=
  filter_from (@entourage T) (fun V => \bigcap_i (map_pair (F i))@^-1` V).

Let initial_fam_ent_filter : Filter initial_fam_ent.
Proof.
apply: filter_from_filter; first by exists setT; exact: entourageT.
move=> P Q eP eQ; exists (P `&` Q); first by exact: filterI.
by move=> [a b]; rewrite /bigcap /= => H; split => i _; have [] := H i.
Qed.

Let initial_fam_ent_refl A : initial_fam_ent A -> diagonal `<=` A.
Proof.
move=> [B ? sBA] [x y]/diagonalP ->; apply/sBA; rewrite /bigcap /= => i _.
exact: entourage_refl.
Qed.

Let initial_fam_ent_inv A : initial_fam_ent A -> initial_fam_ent A^-1.
Proof.
move=> [B ? sBA]; exists B^-1; first exact: entourage_inv.
by move=> ??; exact/sBA.
Qed.

Let initial_fam_ent_split A : initial_fam_ent A -> exists2 B, initial_fam_ent B & B \; B `<=` A.
Proof.
move=> [B entB sBA]; have : exists C, entourage C /\ C \; C `<=` B.
  exact/exists2P/entourage_split_ex.
case=> C [entC CsubB].
exists (\bigcap_i map_pair (F i) @^-1` C); first by exists C.
case=> x y [a /= P Q]. apply/sBA => i /= _.
apply: CsubB. exists ((F i) a) => /=; first by apply: P.
by apply: Q.
Qed.

Let initial_fam_ent_nbhs : nbhs = nbhs_ initial_fam_ent.
Proof.
rewrite predeq2E => x V; split.
  case=> [P [[/= B Q <-] Bx BsubV]].
  have: nbhs ( x)  (\bigcup_(i in B) i).
    by apply: open_nbhs_nbhs; split => //; exists B.
(*  move/nbhsP. [W ? WsubB]; exists ((map_pair f) @^-1` W); first by exists W.
  by move=> ? ?; exact/BsubV/WsubB.
case=> W [V' entV' V'subW] /filterS; apply.
have : nbhs (f x) (xsection V' (f x)) by apply/nbhsP; exists V'.
rewrite (@nbhsE U) => [[O [openU Ofx Osub]]].
(exists (f @^-1` O); repeat split => //); first by exists O => //.
by move=> w ?; apply/mem_set; apply: V'subW; apply/set_mem; exact: Osub.
Qed.*)
Admitted.
 
HB.instance Definition _ := @Nbhs_isUniform.Build (initial_fam_topology F)
  initial_fam_ent initial_fam_ent_filter initial_fam_ent_refl initial_fam_ent_inv
  initial_fam_ent_split initial_fam_ent_nbhs.
End initial_fam_topology_uniform.


From mathcomp Require Import supremum_topology.

Section initial_fam_Topology_with_sup.
Variable (S : choiceType)  (I : pointedType) (T : I -> topologicalType)  (F : forall i :I, (S -> T i)).

Definition Fc := fun i => Topological.class (initial_topology (F i)).

Definition initial_sup_topology := (sup_topology Fc).

Local Notation W := (initial_sup_topology).

Lemma initial_sup_continuous : forall i, continuous ((F i) : W -> T i).
Proof. move=> i; apply/continuousP => A oA.
exists [set  (F i @^-1` A)]; last by rewrite bigcup_set1.
move=> /= O /= -> /= . rewrite /finI_from /=.
exists [fset  (F i @^-1` A)]%fset; last by rewrite set_fset1 bigcap_set1.
by move => ? /=; rewrite inE; move/eqP ->; apply/mem_set; exists i => //; exists A.
Qed.

Lemma cvg_init_sup (G : set_system W) (s : W) :
  Filter G ->
  (forall i, ([set (F i)  @` A | A in G] : set_system _) --> F i s) ->  G --> (s : W) .
Proof.
move=> FG cvfFfs.
move => A -[] /=.
move => _  [[]] H Hop <- [B HB Bs] sBfA/=; rewrite nbhs_filterE.
have BA : B `<=` A.
  apply: subset_trans; last by exact: sBfA.
  by move => y /= By; exists B =>//.
apply: (@filterS _ G _  B) => //; move /(_ B HB): Hop  => /= [] /= C CO Bcap.
(* can´t  apply fsubsetP or subsetP on CO  to obtain the following *)
have Ci : forall (O : set S) , O \in C ->
  exists i : I, exists2 A : set (T i), O = F i @^-1` A & open A.
  by move => O /CO /set_mem //= [i] _ -[O' oO' <-]; exists i; exists O'.
move => {CO} {sBfA} {BA} {A}.
have GC: forall (O : set S), O \in C -> G O.
  move => O OC; move: (OC) => /Ci [i [D OD openD]].
  have : nbhs (F i s) D.
    rewrite nbhsE; exists D => //; split => //.
    by move: Bs; rewrite -Bcap /bigcap /= => /(_ O OC); rewrite OD.
  move/(cvfFfs i D); rewrite nbhs_filterE => //= [[O']] GO' /= O'D.
  apply: filterS; last by exact: GO'.
  by rewrite OD -O'D; apply: preimage_image.
by rewrite -Bcap; apply: filter_bigI => /= O OC; apply: GC.
Qed.

Lemma cvg_image_init_sup (G : set_system W) (s : W) :
  Filter G -> (forall i, (F i) @` setT = setT) ->
  G --> (s : W) <-> (forall i, ([set (F i)  @` A | A in G] : set_system _) --> F i s).
Proof.
move=> FG fsurj; split=> [cvFs|/cvg_init_sup] //.
move=> i A /initial_sup_continuous [B [//= Bop Bs sBAf]].
have /cvFs FB : nbhs (s : W) B by apply: open_nbhs_nbhs.
rewrite nbhs_simpl; exists ((F i) @^-1` A); first exact: filterS FB.
by exact: image_preimage.
Qed.

Lemma continuous_init_sup (V : topologicalType) (f : V -> W) :
 (forall i, continuous ((F i) \o (f : V -> S))) <-> continuous f.
Proof.
split=> cont; last first.
  move=> i x; apply: continuous_comp; first by apply: cont.
  apply: initial_sup_continuous.
move => x A; rewrite /nbhs /= => -[/= B] [Bfrom Bfx BA] /=.
apply: filterS; first by apply: preimage_subset BA.
apply: open_nbhs_nbhs; split => //.
have:= Bfrom => -[] C CO <-; rewrite preimage_bigcup.
apply: bigcup_open => i /CO [] /= D Dsub <-; rewrite preimage_bigcap /=.
rewrite bigcap_fset /= big_seq; apply: bigsetI_open => /= E /Dsub.
move/set_mem => -[j _ [E' oE' <-]]; rewrite -comp_preimage.
by have /continuousP := cont j; apply.
Qed.

End initial_fam_Topology_with_sup.

Section initial_fam_sup_uniform.
Variable (S : choiceType)  (I : pointedType) (T : I -> uniformType)  (F : forall i :I, (S -> T i)).

Local Notation W := (@initial_sup_topology S I T F).

Fail Check (W : uniformType).
End initial_fam_sup_uniform.
