name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'mathcomp/mathcomp:1.13.0-coq-8.14'
          - 'mathcomp/mathcomp:1.13.0-coq-8.15'
          - 'mathcomp/mathcomp:1.14.0-coq-8.14'
          - 'mathcomp/mathcomp:1.14.0-coq-8.15'
          - 'mathcomp/mathcomp:1.15.0-coq-8.14'
          - 'mathcomp/mathcomp:1.15.0-coq-8.15'
          - 'mathcomp/mathcomp:1.15.0-coq-8.16'
          - 'mathcomp/mathcomp-dev:coq-8.14'
          - 'mathcomp/mathcomp-dev:coq-8.15'
          - 'mathcomp/mathcomp-dev:coq-8.16'
          - 'mathcomp/mathcomp-dev:coq-dev'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-mathcomp-analysis.opam'
          custom_image: ${{ matrix.image }}
          install: |
            startGroup "Install dependencies"
              opam pin add -n -y -k path coq-mathcomp-classical $WORKDIR
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam install -y -j 2 coq-mathcomp-classical --deps-only
            endGroup

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
